Import dataset

In [28]:
import pandas as pd

df = pd.read_csv("data/games.csv")

In [29]:
df[['Genre 1', 'Genre 2']] = df['Genres'].str.split(',', n=2, expand=True)[[0, 1]]

df['Genre 1'] = df['Genre 1'].str.strip()
df['Genre 2'] = df['Genre 2'].str.strip()

Drop useless columns

In [30]:
drop_labels = ['AppID', 'About the game', 'Full audio languages', 'Reviews', 'Header image', 'Website','Support url','Support email','Metacritic url', 'User score','Score rank','Notes',
'Average playtime forever','Average playtime two weeks','Median playtime two weeks','Tags','Screenshots','Movies']
df.drop(axis= "columns", columns= drop_labels, inplace = True)

Extract the most important languages

In [31]:
lang_eng = df['Supported languages'].astype(str).str.contains("English")
lang_sp = df['Supported languages'].astype(str).str.contains("Spanish")
lang_de = df['Supported languages'].astype(str).str.contains("German")
lang_fr = df['Supported languages'].astype(str).str.contains("French")

df['Is English'] = lang_eng
df['Is Spanish'] = lang_sp
df['Is German'] = lang_de
df['Is French'] = lang_fr


Delete "Supported languages" column

In [32]:
df.drop(axis= "columns", columns= ['Supported languages'], inplace = True)

Extract the most important languages

In [33]:
cat_single = df['Categories'].astype(str).str.contains("Single-player")
cat_multi = df['Categories'].astype(str).str.contains("Multi-player")

df['Is Single-player'] = cat_single
df['Is Multi-player'] = cat_multi

Delete "Categories" column

In [34]:
df.drop(axis= "columns", columns= ['Categories'], inplace = True)

Extract first two genres

Delete "Genres" column

In [35]:
df.drop(axis= "columns", columns= ['Genres'], inplace = True)

Calculate number of developed and published games 

In [36]:
df

Name  Release date Estimated owners  Peak CCU  \
0             Galactic Bowling  Oct 21, 2008        0 - 20000         0   
1                 Train Bandit  Oct 12, 2017        0 - 20000         0   
2                 Jolt Project  Nov 17, 2021        0 - 20000         0   
3                     Henosis™  Jul 23, 2020        0 - 20000         0   
4        Two Weeks in Painland   Feb 3, 2020        0 - 20000         0   
...                        ...           ...              ...       ...   
85098  Mannerheim's Saloon Car   Jan 2, 2024            0 - 0         0   
85099                 Beer Run   Jan 3, 2024            0 - 0         0   
85100     My Friend The Spider   Jan 4, 2024            0 - 0         0   
85101        Path of Survivors   Jan 8, 2024            0 - 0         0   
85102          The Night Heist   Jan 5, 2024            0 - 0         0   

       Required age  Price  DLC count  Windows    Mac  Linux  ...  \
0                 0  19.99          0     True  False  False  ...   
1                 0   0.99          0     True   True  False  ...   
2                 0   4.99          0     True  False  False  ...   
3                 0   5.99          0     True   True   True  ...   
4                 0   0.00          0     True   True  False  ...   
...             ...    ...        ...      ...    ...    ...  ...   
85098             0   0.00          0     True  False  False  ...   
85099             0   0.00          0     True  False  False  ...   
85100             0   0.00          0     True  False  False  ...   
85101             0   3.99          0     True  False  False  ...   
85102             0   9.99          0     True  False  False  ...   

                  Developers                                   Publishers  \
0      Perpetual FX Creative                        Perpetual FX Creative   
1               Rusty Moyher                                 Wild Rooster   
2              Campião Games                                Campião Games   
3          Odd Critter Games                            Odd Critter Games   
4              Unusual Games                                Unusual Games   
...                      ...                                          ...   
85098      Xamk Game Studios  Sodan ja rauhan keskus Muisti, Päämajamuseo   
85099              955 Games                                    955 Games   
85100                    MCA                                          MCA   
85101          Limited Input                                Limited Input   
85102           Ladell Parks                                 Ladell Parks   

         Genre 1     Genre 2  Is English  Is Spanish Is German Is French  \
0         Casual       Indie        True       False     False     False   
1         Action       Indie        True        True      True      True   
2         Action   Adventure        True       False     False     False   
3      Adventure      Casual        True        True      True      True   
4      Adventure       Indie        True        True     False     False   
...          ...         ...         ...         ...       ...       ...   
85098  Adventure  Simulation        True       False     False     False   
85099     Casual       Indie        True       False     False     False   
85100  Adventure  Simulation        True       False     False     False   
85101     Action      Casual        True       False     False     False   
85102     Casual       Indie        True       False     False     False   

      Is Single-player Is Multi-player  
0                 True            True  
1                 True           False  
2                 True           False  
3                 True           False  
4                 True           False  
...                ...             ...  
85098             True           False  
85099             True           False  
85100             True           False  
85101             True           False  
85102  

Fuction to convert the "Estiated owners" column to int - average of the range

In [37]:
def convert_estimated_owners(owners_range):
    lower, upper = owners_range.split(' - ')
    return (int(lower) + int(upper) /2)

df['Estimated owners (avg)'] = df['Estimated owners'].apply(convert_estimated_owners)

In [38]:
df.drop(axis='columns', columns='Estimated owners', inplace=True)
df.head()


Name  Release date  Peak CCU  Required age  Price  \
0       Galactic Bowling  Oct 21, 2008         0             0  19.99   
1           Train Bandit  Oct 12, 2017         0             0   0.99   
2           Jolt Project  Nov 17, 2021         0             0   4.99   
3               Henosis™  Jul 23, 2020         0             0   5.99   
4  Two Weeks in Painland   Feb 3, 2020         0             0   0.00   

   DLC count  Windows    Mac  Linux  Metacritic score  ...  \
0          0     True  False  False                 0  ...   
1          0     True   True  False                 0  ...   
2          0     True  False  False                 0  ...   
3          0     True   True   True                 0  ...   
4          0     True   True  False                 0  ...   

              Publishers    Genre 1    Genre 2  Is English  Is Spanish  \
0  Perpetual FX Creative     Casual      Indie        True       False   
1           Wild Rooster     Action      Indie        True        True   
2          Campião Games     Action  Adventure        True       False   
3      Odd Critter Games  Adventure     Casual        True        True   
4          Unusual Games  Adventure      Indie        True        True   

  Is German Is French Is Single-player Is Multi-player  Estimated owners (avg)  
0     False     False             True            True                 10000.0  
1      True      True             True           False                 10000.0  
2     False     False             True           False                 10000.0  
3      True      True             True           False                 10000.0  
4     False     False             True           False                 10000.0  

[5 rows x 26 columns]

In [39]:
df['Genre 1'].unique()
df['Genre 1'].isnull().any()

np.True_

Deleting data that wont go to the model

In [40]:
df

Name  Release date  Peak CCU  Required age  Price  \
0             Galactic Bowling  Oct 21, 2008         0             0  19.99   
1                 Train Bandit  Oct 12, 2017         0             0   0.99   
2                 Jolt Project  Nov 17, 2021         0             0   4.99   
3                     Henosis™  Jul 23, 2020         0             0   5.99   
4        Two Weeks in Painland   Feb 3, 2020         0             0   0.00   
...                        ...           ...       ...           ...    ...   
85098  Mannerheim's Saloon Car   Jan 2, 2024         0             0   0.00   
85099                 Beer Run   Jan 3, 2024         0             0   0.00   
85100     My Friend The Spider   Jan 4, 2024         0             0   0.00   
85101        Path of Survivors   Jan 8, 2024         0             0   3.99   
85102          The Night Heist   Jan 5, 2024         0             0   9.99   

       DLC count  Windows    Mac  Linux  Metacritic score  ...  \
0              0     True  False  False                 0  ...   
1              0     True   True  False                 0  ...   
2              0     True  False  False                 0  ...   
3              0     True   True   True                 0  ...   
4              0     True   True  False                 0  ...   
...          ...      ...    ...    ...               ...  ...   
85098          0     True  False  False                 0  ...   
85099          0     True  False  False                 0  ...   
85100          0     True  False  False                 0  ...   
85101          0     True  False  False                 0  ...   
85102          0     True  False  False                 0  ...   

                                        Publishers    Genre 1     Genre 2  \
0                            Perpetual FX Creative     Casual       Indie   
1                                     Wild Rooster     Action       Indie   
2                                    Campião Games     Action   Adventure   
3                                Odd Critter Games  Adventure      Casual   
4                                    Unusual Games  Adventure       Indie   
...                                            ...        ...         ...   
85098  Sodan ja rauhan keskus Muisti, Päämajamuseo  Adventure  Simulation   
85099                                    955 Games     Casual       Indie   
85100                                          MCA  Adventure  Simulation   
85101                                Limited Input     Action      Casual   
85102                                 Ladell Parks     Casual       Indie   

       Is English  Is Spanish Is German Is French Is Single-player  \
0            True       False     False     False             True   
1            True        True      True      True             True   
2            True       False     False     False             True   
3            True        True      True      True             True   
4            True        True     False     False             True   
...           ...         ...       ...       ...              ...   
85098        True       False     False     False             True   
85099        True       False     False     False             True   
85100        True       False     False     False             True   
85101        True       False     False     False             True   
85102        True       False     False     False             True   

      Is Multi-player  Estimated owners (avg)  
0                True                 10000.0  
1               False                 10000.0  
2               False                 10000.0  
3               False                 10000.0  
4               False                 10000.0  
...               ...                     ...  
85098           False                     0.0  
85099           False                     0.0  
85100           False                     0.0  
85101           False                 

In [45]:
name_games = df['Name']
to_drop = ['Name', 'Release date', 'Developers', 'Publishers', 'Genre 2']
df.drop(axis='columns', columns=to_drop, inplace=True)

Converting Genre 1 to int 1,2,3,4... etc. (I dont know if it is good to do it). We will delete missing values from Genre 1. We deleted Genre 2 earlier

In [46]:
df

Peak CCU  Required age  Price  DLC count  Windows    Mac  Linux  \
0             0             0  19.99          0     True  False  False   
1             0             0   0.99          0     True   True  False   
2             0             0   4.99          0     True  False  False   
3             0             0   5.99          0     True   True   True   
4             0             0   0.00          0     True   True  False   
...         ...           ...    ...        ...      ...    ...    ...   
85098         0             0   0.00          0     True  False  False   
85099         0             0   0.00          0     True  False  False   
85100         0             0   0.00          0     True  False  False   
85101         0             0   3.99          0     True  False  False   
85102         0             0   9.99          0     True  False  False   

       Metacritic score  Positive  Negative  ...  Recommendations  \
0                     0         6        11  ...                0   
1                     0        53         5  ...                0   
2                     0         0         0  ...                0   
3                     0         3         0  ...                0   
4                     0        50         8  ...                0   
...                 ...       ...       ...  ...              ...   
85098                 0         0         0  ...                0   
85099                 0         0         0  ...                0   
85100                 0         0         0  ...                0   
85101                 0         0         0  ...                0   
85102                 0         0         0  ...                0   

       Median playtime forever    Genre 1 Is English  Is Spanish  Is German  \
0                            0     Casual       True       False      False   
1                            0     Action       True        True       True   
2                            0     Action       True       False      False   
3                            0  Adventure       True        True       True   
4                            0  Adventure       True        True      False   
...                        ...        ...        ...         ...        ...   
85098                        0  Adventure       True       False      False   
85099                        0     Casual       True       False      False   
85100                        0  Adventure       True       False      False   
85101                        0     Action       True       False      False   
85102                        0     Casual       True       False      False   

       Is French  Is Single-player  Is Multi-player  Estimated owners (avg)  
0          False              True             True                 10000.0  
1           True              True            False                 10000.0  
2          False              True            False                 10000.0  
3           True              True            False                 10000.0  
4          False              True            False                 10000.0  
...          ...               ...              ...                     ...  
85098      False              True            False                     0.0  
85099      False              True            False                     0.0  
85100      False              True            False                     0.0  
85101      False              True            False                     0.0  
85102      False              True            False                     0.0  

[85103 rows x 21 columns]

In [49]:
df.isnull().any()

Peak CCU                   False
Required age               False
Price                      False
DLC count                  False
Windows                    False
Mac                        False
Linux                      False
Metacritic score           False
Positive                   False
Negative                   False
Achievements               False
Recommendations            False
Median playtime forever    False
Genre 1                    False
Is English                 False
Is Spanish                 False
Is German                  False
Is French                  False
Is Single-player           False
Is Multi-player            False
Estimated owners (avg)     False
dtype: bool

In [48]:
df.dropna(inplace=True)

Converting data from Genre 1 to ints

In [51]:
df['Genre 1_encoded'] = pd.factorize(df['Genre 1'])[0] + 1

In [52]:
print(df[['Genre 1', 'Genre 1_encoded']])

         Genre 1  Genre 1_encoded
0         Casual                1
1         Action                2
2         Action                2
3      Adventure                3
4      Adventure                3
...          ...              ...
85098  Adventure                3
85099     Casual                1
85100  Adventure                3
85101     Action                2
85102     Casual                1

[81548 rows x 2 columns]


In [53]:
df

Peak CCU  Required age  Price  DLC count  Windows    Mac  Linux  \
0             0             0  19.99          0     True  False  False   
1             0             0   0.99          0     True   True  False   
2             0             0   4.99          0     True  False  False   
3             0             0   5.99          0     True   True   True   
4             0             0   0.00          0     True   True  False   
...         ...           ...    ...        ...      ...    ...    ...   
85098         0             0   0.00          0     True  False  False   
85099         0             0   0.00          0     True  False  False   
85100         0             0   0.00          0     True  False  False   
85101         0             0   3.99          0     True  False  False   
85102         0             0   9.99          0     True  False  False   

       Metacritic score  Positive  Negative  ...  Median playtime forever  \
0                     0         6        11  ...                        0   
1                     0        53         5  ...                        0   
2                     0         0         0  ...                        0   
3                     0         3         0  ...                        0   
4                     0        50         8  ...                        0   
...                 ...       ...       ...  ...                      ...   
85098                 0         0         0  ...                        0   
85099                 0         0         0  ...                        0   
85100                 0         0         0  ...                        0   
85101                 0         0         0  ...                        0   
85102                 0         0         0  ...                        0   

         Genre 1  Is English Is Spanish  Is German  Is French  \
0         Casual        True      False      False      False   
1         Action        True       True       True       True   
2         Action        True      False      False      False   
3      Adventure        True       True       True       True   
4      Adventure        True       True      False      False   
...          ...         ...        ...        ...        ...   
85098  Adventure        True      False      False      False   
85099     Casual        True      False      False      False   
85100  Adventure        True      False      False      False   
85101     Action        True      False      False      False   
85102     Casual        True      False      False      False   

       Is Single-player  Is Multi-player  Estimated owners (avg)  \
0                  True             True                 10000.0   
1                  True            False                 10000.0   
2                  True            False                 10000.0   
3                  True            False                 10000.0   
4                  True            False                 10000.0   
...                 ...              ...                     ...   
85098              True            False                     0.0   
85099              True            False                     0.0   
85100              True            False                     0.0   
85101              True            False                     0.0   
85102              True            False                     0.0   

       Genre 1_encoded  
0                    1  
1                    2  
2                    2  
3                    3  
4                    3  
...                ...  
85098                3  
85099                1  
85100                3  
85101                2  
85102                1  

[81548 rows x 22 columns]

In [54]:
df.drop(axis='columns', columns='Genre 1', inplace=True)

In [56]:
df.isnull().any()

Peak CCU                   False
Required age               False
Price                      False
DLC count                  False
Windows                    False
Mac                        False
Linux                      False
Metacritic score           False
Positive                   False
Negative                   False
Achievements               False
Recommendations            False
Median playtime forever    False
Is English                 False
Is Spanish                 False
Is German                  False
Is French                  False
Is Single-player           False
Is Multi-player            False
Estimated owners (avg)     False
Genre 1_encoded            False
dtype: bool

Creating model

In [58]:
x = df.drop('Estimated owners (avg)', axis='columns')
y = df['Estimated owners (avg)']

In [71]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report, confusion_matrix

In [65]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.1, random_state=101)

In [75]:
logmodel = LogisticRegression(max_iter=100)
logmodel.fit(X_train, Y_train)
predictions = logmodel.predict(X_test)

c:\Python\ASI-mlops\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [77]:
print(classification_report(Y_test, predictions, zero_division=True))

              precision    recall  f1-score   support

         0.0       1.00      0.00      0.00       799
     10000.0       0.76      0.81      0.78      5581
     45000.0       0.31      0.08      0.13       749
    100000.0       0.20      0.06      0.09       372
    200000.0       0.19      0.01      0.02       270
    450000.0       0.21      0.59      0.31       188
   1000000.0       0.26      0.12      0.16        84
   2000000.0       0.27      0.25      0.26        61
   4500000.0       0.17      0.18      0.18        38
  10000000.0       0.09      0.20      0.12         5
  20000000.0       0.00      0.00      0.00         2
  45000000.0       0.25      0.40      0.31         5
 100000000.0       0.00      0.00      0.00         1
 200000000.0       0.00      1.00      0.00         0

    accuracy                           0.58      8155
   macro avg       0.26      0.26      0.17      8155
weighted avg       0.67      0.58      0.56      8155



In [78]:
print(confusion_matrix(Y_test, predictions))

[[   0  799    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0 4504   65   26    3   59    2    6   10    0   41    0  409  456]
 [   0  390   59   29    2   82    2    8    5    1   23    0   75   73]
 [   0  151   29   21    3   82    1    6    2    0   14    2   36   25]
 [   0   52   23   15    3  126    9    1    2    0    2    1   15   21]
 [   0   12   12   14    3  110    4    5    3    1    1    0   12   11]
 [   0    6    1    2    2   41   10    7    5    1    1    1    5    2]
 [   0    0    2    0    0   15    7   15    5    2    7    0    5    3]
 [   0    0    0    0    0    4    4    7    7    4    7    1    3    1]
 [   0    0    0    0    0    2    0    0    0    1    1    0    0    1]
 [   0    0    0    0    0    0    0    0    1    0    0    0    1    0]
 [   0    0    0    0    0    0    0    0    1    1    0    2    0    1]
 [   0    0    0    0    0    0    0    0    0    0    0    1    0    0]
 [   0    0    0    0    0    0    0    0    0    0